In [ ]:
A = np.array([1,2,3],[4,5,6])
np.sum(A, axis=0)

In [46]:
#test code
A = np.array([[1,2,3],[4,5,6]])
print(A)
B = np.array([[7,8,9],[10,11,12]])
print(B)
print(A-B)
print(np.sum(np.square(A-B)))
C = np.array([[3,4,5]])
print(C)
print(A-C)
D = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(D[A])

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[-6 -6 -6]
 [-6 -6 -6]]
216
[[3 4 5]]
[[-2 -2 -2]
 [ 1  1  1]]
[[2 3 4]
 [5 6 7]]


In [6]:
a = np.array([[1,2,2,3,3,3,3,1,2,1,2,2,1,1,3,3,3,2,2,1,2,2]])
print(a)
x, y = np.histogram(a, bins=np.arange(5))
print(x, y)
np.argmax(x)

[[1 2 2 3 3 3 3 1 2 1 2 2 1 1 3 3 3 2 2 1 2 2]]
[0 6 9 7] [0 1 2 3 4]


2